---
title: "02-trait-analyses"
author: "Anjum K. Gujral"
date: '2025-11-16'
output: html_document
---

#trait data prep
```{r}

library(dplyr)
library(stringr)
library(tidyr)
library(ggplot2)

# load in TRY data
TRY_traits <- read.csv("./data/TRY-traits.csv")

# columns of main interest are 'SpeciesName' , 'TraitName' , 'OriglName', 'OrigValueStr'
# 'OrigUnitStr'

# 'OrigValueStr' has our trait values but it also has other comments, lets drop any rows that are non-numeric
sum(!is.na(TRY_traits$OrigValueStr))

TRY_trait_data1 <- TRY_traits
TRY_trait_data1$OrigValueStr <- as.numeric(TRY_trait_data1$OrigValueStr)
TRY_trait_data1 <- TRY_trait_data1[!is.na(TRY_trait_data1$OrigValueStr),]

# drop any rows that are not traits (i.e. any rows where TraitID == NA)
TRY_trait_data1 <- TRY_trait_data1[!is.na(TRY_trait_data1$TraitID ),]

# clean species names to drop anything after the species epithet (second word)

TRY_trait_data1 <- TRY_trait_data1 %>%
  mutate(SpeciesName = word(SpeciesName, 1, 2))

# drop an underscore in between genus and species epithet
TRY_trait_data1 <- TRY_trait_data1 %>%
  mutate(SpeciesName = paste(word(SpeciesName, 1), 
                               word(SpeciesName, 2), 
                               sep = "_"))

#lets summarize how many obs (unique species) we have for each trait
trait_sample_sizes <- TRY_trait_data1 %>%
  distinct(SpeciesName, TraitName) %>%
  group_by(TraitName) %>%
  summarize(Count = n())

# we can also summarize how many traits we have per species
species_trait_sample_sizes <- aggregate(
  x = TraitName ~ SpeciesName,
  data = TRY_trait_data1,
  FUN = unique
)

species_trait_sample_sizes <- TRY_trait_data1 %>%
  distinct(SpeciesName, OriglName) %>%
  group_by(SpeciesName) %>%
  summarize(unique_orig_list = list(unique(OriglName)))

length(unique(TRY_trait_data1$SpeciesName))

# filter the trait data frame to just look at traits with greater than 13 obs
filtered_traits<- trait_sample_sizes %>%
  filter(Count >= 13)

filtered_traits <- filtered_traits$TraitName

filtered_trait_data <- TRY_trait_data1 %>%
  filter(TraitName %in% filtered_traits)

```

```{r}
unique(filtered_trait_data$Species[filtered_trait_data$TraitName == "Bark thickness"])

```

```{r}
# mfs dont know how to spell so we need to fix some species names

#combine
Abies_lasiocarpa
Abies_lasiocarpus

Cupressus_sp.
Cupressus_spp.


Lithocarpus_densiflora
Lithocarpus_densiflorus

	
Picea_engelmanii
Picea_engelmannii

Prunus_virginia
Prunus_virginiana

Pseudotsuga_menziesii
Pseudotsuga_menziezii

Quercus_garryana
Quercus_garryanna

	
Quercus_kelloggii
Quercus_keloggii

drop 	
Tree_Quercus

```
